//! Transaction-split orchestration (S05 T03). Validates that splits sum to
//! the parent transaction's absolute amount and share its currency; then
//! atomically replaces any existing splits for that transaction and clears
//! the parent's `category_id` (splits carry the categorization).

use rust_decimal::Decimal;
use uuid::Uuid;

use crate::domain::currency::Money;
use crate::domain::error::DomainError;
use crate::domain::transaction::{
    TransactionRepository, TransactionSplit, TransactionSplitRepository,
};

/// 1-cent tolerance on the sum check (guards against rounding when the user
/// splits a $150.00 total as "$50 + $50 + $50" vs re-parsing Decimals).
const SUM_TOLERANCE: Decimal = Decimal::from_parts(1, 0, 0, false, 2); // 0.01

pub struct SplitService<T: TransactionRepository, S: TransactionSplitRepository> {
    txns: T,
    splits: S,
}

/// One entry the caller wants to persist. `id` is generated by the service.
#[derive(Debug, Clone)]
pub struct SplitAllocation {
    pub category_id: String,
    pub amount: Money,
    pub notes: Option<String>,
}

impl<T: TransactionRepository, S: TransactionSplitRepository> SplitService<T, S> {
    pub fn new(txns: T, splits: S) -> Self {
        Self { txns, splits }
    }

    pub fn split_transaction(
        &self,
        transaction_id: &str,
        allocations: Vec<SplitAllocation>,
    ) -> Result<Vec<TransactionSplit>, DomainError> {
        if allocations.len() < 2 {
            return Err(DomainError::Validation(
                "a split needs at least 2 allocations — a single-allocation split is just categorization"
                    .into(),
            ));
        }

        // Load the parent transaction.
        let mut txn =
            self.txns
                .find_by_id(transaction_id)?
                .ok_or_else(|| DomainError::NotFound {
                    entity: "Transaction".into(),
                    id: transaction_id.into(),
                })?;

        // Validate: all splits share the transaction's currency.
        for a in &allocations {
            if a.amount.currency != txn.amount.currency {
                return Err(DomainError::CurrencyMismatch {
                    expected: txn.amount.currency.to_string(),
                    got: a.amount.currency.to_string(),
                });
            }
        }

        // Validate: sum of absolute split amounts equals the absolute
        // transaction amount (within 1-cent tolerance).
        let expected = txn.amount.amount.abs();
        let actual: Decimal = allocations.iter().map(|a| a.amount.amount.abs()).sum();
        if (expected - actual).abs() > SUM_TOLERANCE {
            return Err(DomainError::Validation(format!(
                "split amounts must sum to the transaction's absolute amount {} (got {}, diff {})",
                expected,
                actual,
                (expected - actual).abs()
            )));
        }

        // Replace existing splits for this transaction.
        self.splits.delete_by_transaction(transaction_id)?;
        let mut stored = Vec::with_capacity(allocations.len());
        for a in allocations {
            let split = TransactionSplit::new(
                Uuid::new_v4().to_string(),
                transaction_id.to_string(),
                a.category_id,
                a.amount,
                a.notes,
            )?;
            self.splits.save(&split)?;
            stored.push(split);
        }

        // Clear the parent's category_id — splits now carry the categorization.
        if txn.category_id.is_some() {
            txn.category_id = None;
            self.txns.save(&txn)?;
        }

        Ok(stored)
    }

    /// Remove all splits for a transaction. Parent transaction's category_id
    /// stays NULL (caller can re-run `categorize` or set manually).
    pub fn unsplit_transaction(&self, transaction_id: &str) -> Result<usize, DomainError> {
        self.splits.delete_by_transaction(transaction_id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::account::{Account, AccountRepository as _, AccountType};
    use crate::domain::currency::CurrencyCode;
    use crate::domain::transaction::Transaction;
    use crate::infrastructure::storage::{
        Database, SqliteAccountRepository, SqliteTransactionRepository,
        SqliteTransactionSplitRepository,
    };
    use chrono::NaiveDate;
    use rust_decimal_macros::dec;

    fn setup() -> (Database, String, String, String) {
        let db = Database::in_memory().unwrap();
        SqliteAccountRepository::new(&db)
            .save(
                &Account::new(
                    "acc-1".into(),
                    "Chase".into(),
                    AccountType::Checking,
                    CurrencyCode::USD,
                    "Sky".into(),
                )
                .unwrap(),
            )
            .unwrap();
        let now = chrono::Utc::now().to_rfc3339();
        db.conn()
            .execute(
                "INSERT INTO category_groups (id, name, created_at) VALUES ('g1', 'Grp', ?1)",
                [&now],
            )
            .unwrap();
        db.conn()
            .execute(
                "INSERT INTO categories (id, group_id, name, created_at) VALUES \
                 ('cat-food', 'g1', 'Food', ?1), ('cat-house', 'g1', 'House', ?1)",
                [&now],
            )
            .unwrap();

        let mut t = Transaction::new(
            "txn-1".into(),
            "acc-1".into(),
            NaiveDate::from_ymd_opt(2026, 4, 10).unwrap(),
            Money::new(dec!(-150.00), CurrencyCode::USD),
        )
        .unwrap();
        t.external_id = Some("ext-1".into());
        SqliteTransactionRepository::new(&db).save(&t).unwrap();

        (db, "txn-1".into(), "cat-food".into(), "cat-house".into())
    }

    fn service(
        db: &Database,
    ) -> SplitService<SqliteTransactionRepository<'_>, SqliteTransactionSplitRepository<'_>> {
        SplitService::new(
            SqliteTransactionRepository::new(db),
            SqliteTransactionSplitRepository::new(db),
        )
    }

    fn alloc(cat: &str, amount: Decimal, notes: Option<&str>) -> SplitAllocation {
        SplitAllocation {
            category_id: cat.into(),
            amount: Money::new(amount, CurrencyCode::USD),
            notes: notes.map(|s| s.to_string()),
        }
    }

    #[test]
    fn happy_path_two_way_split() {
        let (db, txn_id, food, house) = setup();
        let svc = service(&db);
        let splits = svc
            .split_transaction(
                &txn_id,
                vec![
                    alloc(&food, dec!(-100.00), Some("groceries")),
                    alloc(&house, dec!(-50.00), None),
                ],
            )
            .unwrap();
        assert_eq!(splits.len(), 2);

        // Parent category_id was cleared.
        let parent = SqliteTransactionRepository::new(&db)
            .find_by_id(&txn_id)
            .unwrap()
            .unwrap();
        assert!(parent.category_id.is_none());
    }

    #[test]
    fn rejects_sum_mismatch() {
        let (db, txn_id, food, house) = setup();
        let svc = service(&db);
        let err = svc
            .split_transaction(
                &txn_id,
                vec![
                    alloc(&food, dec!(-100), None),
                    alloc(&house, dec!(-10), None),
                ],
            )
            .unwrap_err();
        match err {
            DomainError::Validation(msg) => assert!(msg.contains("sum")),
            other => panic!("expected Validation, got {other:?}"),
        }
    }

    #[test]
    fn accepts_one_cent_tolerance() {
        let (db, txn_id, food, house) = setup();
        let svc = service(&db);
        // $150 total; $75.00 + $75.00 — exact; also try $74.995 + $75.005 boundary.
        svc.split_transaction(
            &txn_id,
            vec![
                alloc(&food, dec!(-75.00), None),
                alloc(&house, dec!(-75.00), None),
            ],
        )
        .unwrap();
    }

    #[test]
    fn rejects_single_allocation() {
        let (db, txn_id, food, _) = setup();
        let svc = service(&db);
        let err = svc
            .split_transaction(&txn_id, vec![alloc(&food, dec!(-150), None)])
            .unwrap_err();
        assert!(matches!(err, DomainError::Validation(_)));
    }

    #[test]
    fn rejects_currency_mismatch() {
        let (db, txn_id, food, house) = setup();
        let svc = service(&db);
        let err = svc
            .split_transaction(
                &txn_id,
                vec![
                    alloc(&food, dec!(-100), None),
                    SplitAllocation {
                        category_id: house,
                        amount: Money::new(dec!(-50), CurrencyCode::BRL),
                        notes: None,
                    },
                ],
            )
            .unwrap_err();
        assert!(matches!(err, DomainError::CurrencyMismatch { .. }));
    }

    #[test]
    fn rejects_unknown_transaction() {
        let (db, _, food, house) = setup();
        let svc = service(&db);
        let err = svc
            .split_transaction(
                "txn-ghost",
                vec![
                    alloc(&food, dec!(-100), None),
                    alloc(&house, dec!(-50), None),
                ],
            )
            .unwrap_err();
        assert!(matches!(err, DomainError::NotFound { .. }));
    }

    #[test]
    fn re_splitting_replaces_existing() {
        let (db, txn_id, food, house) = setup();
        let svc = service(&db);
        svc.split_transaction(
            &txn_id,
            vec![
                alloc(&food, dec!(-100), None),
                alloc(&house, dec!(-50), None),
            ],
        )
        .unwrap();
        // Re-split with different allocation.
        svc.split_transaction(
            &txn_id,
            vec![
                alloc(&food, dec!(-80), None),
                alloc(&house, dec!(-70), None),
            ],
        )
        .unwrap();

        let splits = SqliteTransactionSplitRepository::new(&db)
            .find_by_transaction(&txn_id)
            .unwrap();
        assert_eq!(splits.len(), 2);
        let amounts: Vec<Decimal> = splits.iter().map(|s| s.amount.amount).collect();
        assert!(amounts.contains(&dec!(-80)));
        assert!(amounts.contains(&dec!(-70)));
    }

    #[test]
    fn unsplit_removes_all_splits() {
        let (db, txn_id, food, house) = setup();
        let svc = service(&db);
        svc.split_transaction(
            &txn_id,
            vec![
                alloc(&food, dec!(-100), None),
                alloc(&house, dec!(-50), None),
            ],
        )
        .unwrap();
        let removed = svc.unsplit_transaction(&txn_id).unwrap();
        assert_eq!(removed, 2);
        assert!(
            SqliteTransactionSplitRepository::new(&db)
                .find_by_transaction(&txn_id)
                .unwrap()
                .is_empty()
        );
    }

    #[test]
    fn clears_parent_category_id_when_splitting_an_already_categorized_row() {
        let (db, txn_id, food, house) = setup();
        let mut t = SqliteTransactionRepository::new(&db)
            .find_by_id(&txn_id)
            .unwrap()
            .unwrap();
        t.category_id = Some(food.clone());
        SqliteTransactionRepository::new(&db).save(&t).unwrap();

        let svc = service(&db);
        svc.split_transaction(
            &txn_id,
            vec![
                alloc(&food, dec!(-100), None),
                alloc(&house, dec!(-50), None),
            ],
        )
        .unwrap();

        let after = SqliteTransactionRepository::new(&db)
            .find_by_id(&txn_id)
            .unwrap()
            .unwrap();
        assert!(after.category_id.is_none());
    }
}
